defaults: &defaults
    secret_token: 'somethingsecure' # 'rake secret' to generate a token
    secret_key: 'somethingsecure' # 'rake secret' to generate a token
    url_host: "example.test"
    devise_mailer_sender: "devise@example.com"
    mailer_address: "smtpout.secureserver.net" # for example, this is godaddy.com
    mailer_port: 80
    mailer_domain: "example.com"
    mailer_user_name: "myinfo@example.com"
    mailer_password: "123123"
    ga_tracker: "UA-xxxxxxxx-X"
    ga_tracker_domain: "example.test"
    twitter_consumer_key: xxxxx # register your application at dev.twitter.co,
    twitter_consumer_secret: xxxx
    legal_disclaimer_link: "http://ourdisclaimer.com/?i=YOUR-SITE-NAME"

development:
    <<: *defaults